// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbramjivmxpqfvfnmvsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1icmFtaml2bXhwcWZ2Zm5tdnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTY0OTQsImV4cCI6MjA3MDY3MjQ5NH0.qt-8HrSQx-My6dv2CPgFI9enezDHUiaXEamvSE3-frc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});