"""Adicionar next_reset_date na tabela user

Revision ID: 5f971c7710ec
Revises: bfd1cdcd0f3e
Create Date: 2026-03-04 18:52:46.052405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f971c7710ec'
down_revision = 'bfd1cdcd0f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_reset_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('next_reset_date')

    # ### end Alembic commands ###
